### PR TITLE
initial files for download website

### PR DESCRIPTION
**Pull request by dangunter**
Docusaurus based download website files

See `website/README.md` for some basic commands.

Deployment to GH-pages is the goal, but not yet attempted!

### CODE REVIEW

**Comment by dangunter** [comment]
For this PR, I think "success" would be that Michael, or anyone else, can recreate the site (as it stands) locally. I think deployment and the actual download content can be in other PRs.

**Comment by MichaelPesce** [comment]
@dangunter I'm getting an error trying to start this locally:

Screenshot 2024-12-13 at 8 11 27 AM

I installed the node packages, and tried running the start command from both `idaes-flowsheet-processor-ui/website/docs/` and `idaes-flowsheet-processor-ui/website/`

**Comment by dangunter** [comment]
@MichaelPesce I added some missing files, that should solve the error message above.

**Comment by MichaelPesce** [comment]
@dangunter works for me now!

**Review by MichaelPesce — APPROVED** [review]

**Pull request closed without merging**
